{{- if and .Values.controller.enabled .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "azurelustre.fullname" . }}-controller-secret-binding
  labels:
    {{- include "azurelustre.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "azurelustre.serviceAccountNameController" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "azurelustre.fullname" . }}-controller-secret-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
