{{- if .Values.csidriver.create }}
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ .Values.csidriver.name }}
  labels:
    {{- include "azurelustre.labels" . | nindent 4 }}
spec:
  fsGroupPolicy: {{ .Values.csidriver.fsGroupPolicy }}
  attachRequired: {{ .Values.csidriver.attachRequired }}
  podInfoOnMount: {{ .Values.csidriver.podInfoOnMount }}
{{- end }}
