apiVersion: v1
entries:
  azurelustre-csi-driver:
  - apiVersion: v1
    appVersion: v0.3.0
    created: "2025-10-13T20:04:40.359792859+02:00"
    description: Azure Lustre CSI Driver Helm chart
    digest: 9945f25e934688b8d080bb0c6adcd3d4316421638154c22dbb221a0920a3d683
    keywords:
    - storage
    - csi
    - azure
    - lustre
    name: azurelustre-csi-driver
    urls:
    - https://raw.githubusercontent.com/wolfgang-desalvador/azurelustre-csi-driver/refs/heads/wdesalvador/add-helm-chart-support/charts/v0.3.0/azurelustre-csi-driver-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v1
    appVersion: latest
    created: "2025-10-13T20:04:40.352317144+02:00"
    description: Azure Lustre CSI Driver Helm chart
    digest: fa20c0a8ed6529740c68229ff77a26e0823835ff9e9ba2c0cc7f157bf9b4b0e3
    keywords:
    - storage
    - csi
    - azure
    - lustre
    name: azurelustre-csi-driver
    urls:
    - https://raw.githubusercontent.com/wolfgang-desalvador/azurelustre-csi-driver/refs/heads/wdesalvador/add-helm-chart-support/charts/latest/azurelustre-csi-driver-v0.0.0.tgz
    version: v0.0.0
generated: "2025-10-13T20:04:40.343513652+02:00"
