{{- if and .Values.controller.enabled .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "azurelustre.fullname" . }}-controller-secret-role
  labels:
    {{- include "azurelustre.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create"]
{{- end }}
