{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "azurelustre.serviceAccountNameNode" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "azurelustre.labels" . | nindent 4 }}
{{- if .Values.imagePullSecrets }}
imagePullSecrets:
{{- range .Values.imagePullSecrets }}
  - name: {{ . }}
{{- end }}
{{- end }}
{{- end }}
